---
version: '3'

services:
  proxy_pool:
    image: jhao104/proxy_pool
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mRx740M<g~n
    volumes:
      - ./bgp_he.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: bgp_web